name: Terraform CI

on: [push, pull_request]

jobs:
  test:
    name: Terraform Checks
    strategy:
      matrix:
        os: [ubuntu-24.04, windows-2025, macos-15]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup
        uses: hashicorp/setup-terraform@v2.0.3
        with:
          terraform_version: 1.0.4

      - name: Init
        run: terraform init -backend=false

      - name: Terraform Format
        run: terraform fmt -check

      - name: Validate
        run: terraform validate
        env:
          AWS_DEFAULT_REGION: us-west-1
